baseURL: "https://isexychat.com"
languageCode: "en-us"
title: "iSexyChat Blog"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
  category: categories
  tag: tags
